[package]
name = "spanner-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
bb8 = "0.7"
prost = "0.8"
prost-types = "0.8"
thiserror = "1.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "net"] }
tonic = "0.5"
tonic-types = "0.3"

[dev-dependencies]
async-trait = "0.1"
testcontainers = "0.12"
reqwest = "0.11"

[build-dependencies]
tonic-build = "0.5"

[lib]
doctest = false # TODO: move generated code to another crate to only disable this in that crate.
